### ISSUE TITLE
规则文件更新策略

### ISSUE THREAD

**Issue by MrLawrenc** [hongwen1993/fast-drools-spring-boot-starter#13]
version：8.0.3
1. 是否考虑提供一个 关闭自动更新规则文件手动更新 的策略配置，因为某些编辑器有自动保存，今天试用了一下，发现没编辑完就保存了，导致更新到了错误的规则文件，从而导致程序报错
2. 建议优化下日志，基本都是info，而且部分exception是控制台输出的，没有记为log

**Comment by hongwen1993** [comment]
安排了，下个版本给你一个交代！
