### ISSUE TITLE
Dynamic update issue

### ISSUE THREAD

**Issue by ajitkumargiri** [hongwen1993/fast-drools-spring-boot-starter#15]
Hi Author,
What is the best way to load drl file dynamically?
Because all the rule files are inside the application resources. 
If we need to update one drl file what we need to do.

Thanks in advance.

**Comment by heyaheng1995** [comment]
我收到了。看到后会尽快回复。

**Comment by tangwan** [comment]
> Hi Author, What is the best way to load drl file dynamically? Because all the rule files are inside the application resources. If we need to update one drl file what we need to do.
> 
> Thanks in advance.

drools use lancher Classloader, while devtools treats our self-written model as a class that can change at any time, so the Restart ClassLoader is used for loading (for fast hot deployment). devtools will have two class loaders, a Classloader that loads the classes that don't change (third-party Jar packages) and a ClassLoader that loads the classes that do change, called the Restart ClassLoader. When the A Class loaded by the Launcher ClassLoader is compared with the A class loaded by the Restart ClassLoader, it is found to be inconsistent, so the drools engine cannot recognize it naturally.

you can put `.drl` file outside your project.
```
spring:
   drools:  
      path: C:/drools/
```

**Comment by heyaheng1995** [comment]
我收到了。看到后会尽快回复。
