### ISSUE TITLE
这个repo能提PR么？

### ISSUE THREAD

**Issue by Michael-crazyman** [hongwen1993/fast-drools-spring-boot-starter#2]

**Comment by Michael-crazyman** [comment]
我看了一下Up主源码 感觉有些代码写的不是很讲究 所以想问下能不能提PR? 我拉个分支改一下？并且想问下咱们这个repo都没有UT/IT么？那如何保证代码质量以及如何保证以后能放心的重构？

**Comment by hongwen1993** [comment]
邀请你了，大佬。顺便问一下，可否加微信或者QQ互相交流学习！
