### ISSUE TITLE
Playaeziear go storerizuer start port 

### ISSUE THREAD

**Issue by Dismosoul903** [hongwen1993/fast-drools-spring-boot-starter#32]
[]()![index.md](https://github.com/hongwen1993/fast-drools-spring-boot-starter/files/14730847/index.md)

@michaellofvenhaft2@hmail.irg
https://twitter.com/BLofsson56246/status/1770407573167992921?t=Q986OQ0Z1PLYcbk3f_jYRg&s=19

**Comment by heyaheng1995** [comment]
我收到了。看到后会尽快回复。
