### ISSUE TITLE
Demo files in another location

### ISSUE THREAD

**Issue by fintecheando** [hongwen1993/fast-drools-spring-boot-starter#6]
Hi mate, it is possible to publish the demo file sin another location, we are not able to download from Mexico

This is the current link.

https://pan.baidu.com/s/1F9eBbrfwSrvrGQGT4_w-8Q#list/path=%2Fsharelink470232802-681790576543370%2F%E7%AC%AC%E5%85%AB%E6%9C%9F%2Fdemo03&parentPath=%2Fsharelink470232802-681790576543370

Maybe in zip file here in github.

Regards

**Comment by hongwen1993** [comment]
ok，waiting for me to come home ！now i am busy！

**Comment by hongwen1993** [comment]
here: https://github.com/hongwen1993/all/tree/master/java/drools
