### ISSUE TITLE
可以不传递drl文件名称，自动使用所有符合的规则文件吗？

### ISSUE THREAD

**Issue by liu-xinhui** [hongwen1993/fast-drools-spring-boot-starter#7]
官方提供的方法大都是自动使用drl，不需要传递文件名称，这个库怎么做呢？

**Comment by hongwen1993** [comment]
官方的也需要指定规则文件，一样的。我不太清楚你的问题是什么，是需要在调用规则文件的时候，默认调用全部规则去评估？如果是这样的话，那这样的设计是不合理的。因为会存在大量的规则文件，通常我们指定规则文件名称，加载指定的规则文件，然后再在上下文中激活指定的 agenda group 从而形成一个直观的链式调用过程。

**Comment by liu-xinhui** [comment]
[https://github.com/kiegroup/drools/blob/master/drools-examples-api/default-kiesession/src/main/java/org/drools/example/api/defaultkiesession/DefaultKieSessionExample.java](https://github.com/kiegroup/drools/blob/master/drools-examples-api/default-kiesession/src/main/java/org/drools/example/api/defaultkiesession/DefaultKieSessionExample.java)
官方demo是会默认读取所有classpath下面的drl文件的，并不能指定文件名称，所有的demo我都看了，都不能指定文件名称

**Comment by liu-xinhui** [comment]
确实指定文件名称更合理
