### ISSUE TITLE
集成到spring boot后无效

### ISSUE THREAD

**Issue by liu-xinhui** [hongwen1993/fast-drools-spring-boot-starter#8]
spring boot版本2.3.0.RELEASE
集成后使用**单元测试一切正常**，但是**项目启动后再controller中**调用无效。
经寻找是<hw-drools.version>7.22.0.Final</hw-drools.version>
7.22.0.Final这个版本的bug，升级到7.37.0.Final后无此问题。

**Comment by hongwen1993** [comment]
谢谢，晚上更新到maven center中

**Comment by hongwen1993** [comment]
我测试用例都是用spring boot 2.1.5.RELEASE，可能版本有些地方有冲突。我目前已经更新到7.37.0.Final，预计过一会可以在Maven Center中搜索到。
同时，我把项目的版本号与Kie的版本号统一起来了，方便大家使用。刚刚更新了一版：7.37.0.Final
同时谢谢大佬提的Issues！

[查看演示动画](https://cdn.u1.huluxia.com/g4/M03/42/93/rBAAdl7LYKaAbhYRAAtxXzA41Ac306.gif)

**Comment by liu-xinhui** [comment]
好的

**Comment by weikelujava** [comment]
确实按照文档中配置的pom依赖引用8.0.1-SNAPSHOT版本的也会出现这个错误。目前正在尝试7.37.0.Final版本。

**Comment by hongwen1993** [comment]
@weikelujava 
Kie版本回滚到7.37.0之后，重新提交了一个版本，8.0.2-SNAPSHOT；
不过中央仓库上要过一会才能拉到，maybe；
谢谢！！！！

**Comment by hongwen1993** [comment]
@weikelujava 
中央仓库没有更新，不知道为什么，我试试看再提交一个版本。谢谢！更新了马上通知你！

**Comment by hongwen1993** [comment]
@weikelujava 
更新了，8.0.3 版本
