### ISSUE TITLE
获取KieSession的性能问题

### ISSUE THREAD

**Issue by 0x9bb1** [hongwen1993/fast-drools-spring-boot-starter#9]
- 版本： `2.2.0.2`
- 描述：
    在获取`kieSession`时，在规则小于10，执行时间为`200ms`左右。尝试打开`drools.sessionCache`选项，并没有明显的性能提升。
    请教`kieSession`有没有哪些可用的缓存方案

**Comment by hongwen1993** [comment]
有状态的KieSession对性能有显著的提升，但是不适用于很多业务场景。Drools的性能问题，一直饱受诟病，我也在做各种尝试，谢谢支持。

**Comment by 0x9bb1** [comment]
> 有状态的KieSession对性能有显著的提升，但是不适用于很多业务场景。Drools的性能问题，一直饱受诟病，我也在做各种尝试，谢谢支持。

目前我的做法是使用本地缓存来缓存`kieSession`，当缓存命中时，有100ms左右的性能提升。坏处是占用了宝贵的堆内存。抛砖引玉，期待作者大大更好的解决方案。

**Comment by hongwen1993** [comment]
你为什么这么熟练啊？（冬马你好）

**Comment by liu-xinhui** [comment]
1000行的决策表，生成KieSession要40秒呀，并且第二次依然要这么久，咋办呢

**Comment by hongwen1993** [comment]
莫慌莫慌，我回去想想法子，不行只能用有状态的kiesession了！




| |
洪闻
|
|
邮箱：15700051127@163.com
|

签名由 网易邮箱大师 定制

在2020年09月03日 11:36，liu-xinhui 写道：

1000行的决策表，生成KieSession要40秒呀，并且第二次依然要这么久，咋办呢

**Comment by liu-xinhui** [comment]
@hongwen1993 期待您的改进
